name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push to Docker Hub
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/docker-node-app .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/docker-node-app

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 023704516525.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and push to AWS ECR
        run: |
          docker tag docker-node-app 023704516525.dkr.ecr.us-east-1.amazonaws.com/docker-node-app
          docker push 023704516525.dkr.ecr.us-east-1.amazonaws.com/docker-node-app
